// Generated by rstantools.  Do not edit by hand.

/*
    compdag is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    compdag is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with compdag.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_compDAG1_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 39> locations_array__ =
  {" (found before start of program)",
  " (in 'compDAG1', line 10, column 2 to column 11)",
  " (in 'compDAG1', line 11, column 2 to column 21)",
  " (in 'compDAG1', line 14, column 2 to column 20)",
  " (in 'compDAG1', line 15, column 2 to column 19)",
  " (in 'compDAG1', line 16, column 2 to column 18)",
  " (in 'compDAG1', line 31, column 2 to column 20)",
  " (in 'compDAG1', line 18, column 4 to column 20)",
  " (in 'compDAG1', line 17, column 16 to line 19, column 3)",
  " (in 'compDAG1', line 17, column 2 to line 19, column 3)",
  " (in 'compDAG1', line 20, column 2 to column 19)",
  " (in 'compDAG1', line 21, column 2 to column 11)",
  " (in 'compDAG1', line 32, column 17 to column 67)",
  " (in 'compDAG1', line 32, column 2 to column 67)",
  " (in 'compDAG1', line 24, column 2 to column 17)",
  " (in 'compDAG1', line 25, column 17 to column 56)",
  " (in 'compDAG1', line 25, column 2 to column 56)",
  " (in 'compDAG1', line 27, column 4 to column 52)",
  " (in 'compDAG1', line 26, column 15 to line 28, column 3)",
  " (in 'compDAG1', line 26, column 2 to line 28, column 3)",
  " (in 'compDAG1', line 2, column 2 to column 19)",
  " (in 'compDAG1', line 3, column 2 to column 20)",
  " (in 'compDAG1', line 4, column 2 to column 20)",
  " (in 'compDAG1', line 5, column 9 to column 11)",
  " (in 'compDAG1', line 5, column 12 to column 13)",
  " (in 'compDAG1', line 5, column 2 to column 18)",
  " (in 'compDAG1', line 6, column 9 to column 11)",
  " (in 'compDAG1', line 6, column 12 to column 13)",
  " (in 'compDAG1', line 6, column 2 to column 18)",
  " (in 'compDAG1', line 7, column 2 to column 11)",
  " (in 'compDAG1', line 11, column 17 to column 19)",
  " (in 'compDAG1', line 11, column 10 to column 12)",
  " (in 'compDAG1', line 14, column 9 to column 11)",
  " (in 'compDAG1', line 14, column 12 to column 14)",
  " (in 'compDAG1', line 15, column 9 to column 11)",
  " (in 'compDAG1', line 15, column 12 to column 13)",
  " (in 'compDAG1', line 16, column 9 to column 11)",
  " (in 'compDAG1', line 16, column 12 to column 13)",
  " (in 'compDAG1', line 31, column 9 to column 10)"};
#include <stan_meta_header.hpp>
class model_compDAG1 final : public model_base_crtp<model_compDAG1> {
private:
  int n;
  int p1;
  int p2;
  Eigen::Matrix<double,-1,-1> y1_data__;
  Eigen::Matrix<double,-1,-1> y2_data__;
  double mu2;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> y1{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> y2{nullptr, 0, 0};
public:
  ~model_compDAG1() {}
  model_compDAG1(stan::io::var_context& context__, unsigned int
                 random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_compDAG1_namespace::model_compDAG1";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 20;
      context__.validate_dims("data initialization", "n", "int",
        std::vector<size_t>{});
      n = std::numeric_limits<int>::min();
      current_statement__ = 20;
      n = context__.vals_i("n")[(1 - 1)];
      current_statement__ = 20;
      stan::math::check_greater_or_equal(function__, "n", n, 0);
      current_statement__ = 21;
      context__.validate_dims("data initialization", "p1", "int",
        std::vector<size_t>{});
      p1 = std::numeric_limits<int>::min();
      current_statement__ = 21;
      p1 = context__.vals_i("p1")[(1 - 1)];
      current_statement__ = 21;
      stan::math::check_greater_or_equal(function__, "p1", p1, 0);
      current_statement__ = 22;
      context__.validate_dims("data initialization", "p2", "int",
        std::vector<size_t>{});
      p2 = std::numeric_limits<int>::min();
      current_statement__ = 22;
      p2 = context__.vals_i("p2")[(1 - 1)];
      current_statement__ = 22;
      stan::math::check_greater_or_equal(function__, "p2", p2, 0);
      current_statement__ = 23;
      stan::math::validate_non_negative_index("y1", "p1", p1);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("y1", "n", n);
      current_statement__ = 25;
      context__.validate_dims("data initialization", "y1", "double",
        std::vector<size_t>{static_cast<size_t>(p1), static_cast<size_t>(n)});
      y1_data__ = Eigen::Matrix<double,-1,-1>::Constant(p1, n,
                    std::numeric_limits<double>::quiet_NaN());
      new (&y1) Eigen::Map<Eigen::Matrix<double,-1,-1>>(y1_data__.data(), p1,
        n);
      {
        std::vector<local_scalar_t__> y1_flat__;
        current_statement__ = 25;
        y1_flat__ = context__.vals_r("y1");
        current_statement__ = 25;
        pos__ = 1;
        current_statement__ = 25;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 25;
          for (int sym2__ = 1; sym2__ <= p1; ++sym2__) {
            current_statement__ = 25;
            stan::model::assign(y1, y1_flat__[(pos__ - 1)],
              "assigning variable y1", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 25;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 26;
      stan::math::validate_non_negative_index("y2", "p2", p2);
      current_statement__ = 27;
      stan::math::validate_non_negative_index("y2", "n", n);
      current_statement__ = 28;
      context__.validate_dims("data initialization", "y2", "double",
        std::vector<size_t>{static_cast<size_t>(p2), static_cast<size_t>(n)});
      y2_data__ = Eigen::Matrix<double,-1,-1>::Constant(p2, n,
                    std::numeric_limits<double>::quiet_NaN());
      new (&y2) Eigen::Map<Eigen::Matrix<double,-1,-1>>(y2_data__.data(), p2,
        n);
      {
        std::vector<local_scalar_t__> y2_flat__;
        current_statement__ = 28;
        y2_flat__ = context__.vals_r("y2");
        current_statement__ = 28;
        pos__ = 1;
        current_statement__ = 28;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 28;
          for (int sym2__ = 1; sym2__ <= p2; ++sym2__) {
            current_statement__ = 28;
            stan::model::assign(y2, y2_flat__[(pos__ - 1)],
              "assigning variable y2", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 28;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 29;
      context__.validate_dims("data initialization", "mu2", "double",
        std::vector<size_t>{});
      mu2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 29;
      mu2 = context__.vals_r("mu2")[(1 - 1)];
      current_statement__ = 30;
      stan::math::validate_non_negative_index("m1", "p1", p1);
      current_statement__ = 31;
      stan::math::validate_positive_index("m1", "p2", p2);
      current_statement__ = 32;
      stan::math::validate_non_negative_index("mt1", "p2", p2);
      current_statement__ = 33;
      stan::math::validate_non_negative_index("mt1", "p1", p1);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("mx1", "p2", p2);
      current_statement__ = 35;
      stan::math::validate_non_negative_index("mx1", "n", n);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("mx", "p2", p2);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("mx", "n", n);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("log_lik", "n", n);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + (p1 * (p2 - 1));
  }
  inline std::string model_name() const final {
    return "model_compDAG1";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_compDAG1_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ pi1 = DUMMY_VAR__;
      current_statement__ = 1;
      pi1 = in__.template read<local_scalar_t__>();
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> m1 =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(p1,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p2, DUMMY_VAR__));
      current_statement__ = 2;
      m1 = in__.template read_constrain_simplex<
             std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>,
             jacobian__>(lp__, p1, p2);
      Eigen::Matrix<local_scalar_t__,-1,-1> mt1 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(p2, p1, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,-1> mx1 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(p2, n, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,-1> mx =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(p2, n, DUMMY_VAR__);
      current_statement__ = 9;
      for (int i = 1; i <= p1; ++i) {
        current_statement__ = 7;
        stan::model::assign(mt1,
          stan::model::rvalue(m1, "m1", stan::model::index_uni(i)),
          "assigning variable mt1", stan::model::index_omni(),
          stan::model::index_uni(i));
      }
      current_statement__ = 10;
      stan::model::assign(mx1,
        stan::math::multiply(stan::math::multiply(pi1, mt1), y1),
        "assigning variable mx1");
      current_statement__ = 11;
      stan::model::assign(mx, mx1, "assigning variable mx");
      {
        current_statement__ = 14;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(pi1, 1, 1));
        current_statement__ = 16;
        for (int j = 1; j <= p1; ++j) {
          current_statement__ = 15;
          lp_accum__.add(stan::math::dirichlet_lpdf<propto__>(
                           stan::model::rvalue(m1, "m1",
                             stan::model::index_uni(j)),
                           stan::math::rep_vector((1.0 / p2), p2)));
        }
        current_statement__ = 19;
        for (int i = 1; i <= n; ++i) {
          current_statement__ = 17;
          lp_accum__.add(stan::math::dirichlet_lpdf<false>(
                           stan::model::rvalue(y2, "y2",
                             stan::model::index_omni(),
                             stan::model::index_uni(i)),
                           stan::math::add(
                             stan::model::rvalue(mx, "mx",
                               stan::model::index_omni(),
                               stan::model::index_uni(i)), mu2)));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_compDAG1_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double pi1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      pi1 = in__.template read<local_scalar_t__>();
      std::vector<Eigen::Matrix<double,-1,1>> m1 =
        std::vector<Eigen::Matrix<double,-1,1>>(p1,
          Eigen::Matrix<double,-1,1>::Constant(p2,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 2;
      m1 = in__.template read_constrain_simplex<
             std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>,
             jacobian__>(lp__, p1, p2);
      Eigen::Matrix<double,-1,-1> mt1 =
        Eigen::Matrix<double,-1,-1>::Constant(p2, p1,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> mx1 =
        Eigen::Matrix<double,-1,-1>::Constant(p2, n,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> mx =
        Eigen::Matrix<double,-1,-1>::Constant(p2, n,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(pi1);
      for (int sym1__ = 1; sym1__ <= p2; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= p1; ++sym2__) {
          out__.write(m1[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 9;
      for (int i = 1; i <= p1; ++i) {
        current_statement__ = 7;
        stan::model::assign(mt1,
          stan::model::rvalue(m1, "m1", stan::model::index_uni(i)),
          "assigning variable mt1", stan::model::index_omni(),
          stan::model::index_uni(i));
      }
      current_statement__ = 10;
      stan::model::assign(mx1,
        stan::math::multiply(stan::math::multiply(pi1, mt1), y1),
        "assigning variable mx1");
      current_statement__ = 11;
      stan::model::assign(mx, mx1, "assigning variable mx");
      if (emit_transformed_parameters__) {
        out__.write(mt1);
        out__.write(mx1);
        out__.write(mx);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(n,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 13;
      for (int i = 1; i <= n; ++i) {
        current_statement__ = 12;
        stan::model::assign(log_lik,
          stan::math::dirichlet_lpdf<false>(
            stan::model::rvalue(y2, "y2", stan::model::index_omni(),
              stan::model::index_uni(i)),
            stan::math::add(
              stan::model::rvalue(mx, "mx", stan::model::index_omni(),
                stan::model::index_uni(i)), mu2)),
          "assigning variable log_lik", stan::model::index_uni(i));
      }
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ pi1 = DUMMY_VAR__;
      current_statement__ = 1;
      pi1 = in__.read<local_scalar_t__>();
      out__.write(pi1);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> m1 =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(p1,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p2, DUMMY_VAR__));
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= p2; ++sym1__) {
        current_statement__ = 2;
        for (int sym2__ = 1; sym2__ <= p1; ++sym2__) {
          current_statement__ = 2;
          stan::model::assign(m1, in__.read<local_scalar_t__>(),
            "assigning variable m1", stan::model::index_uni(sym2__),
            stan::model::index_uni(sym1__));
        }
      }
      out__.write_free_simplex(m1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "pi1", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "m1", "double",
        std::vector<size_t>{static_cast<size_t>(p1), static_cast<size_t>(p2)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ pi1 = DUMMY_VAR__;
      current_statement__ = 1;
      pi1 = context__.vals_r("pi1")[(1 - 1)];
      out__.write(pi1);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> m1 =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(p1,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p2, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> m1_flat__;
        current_statement__ = 2;
        m1_flat__ = context__.vals_r("m1");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= p2; ++sym1__) {
          current_statement__ = 2;
          for (int sym2__ = 1; sym2__ <= p1; ++sym2__) {
            current_statement__ = 2;
            stan::model::assign(m1, m1_flat__[(pos__ - 1)],
              "assigning variable m1", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 2;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_simplex(m1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"pi1", "m1"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"mt1", "mx1", "mx"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(p1),
                  static_cast<size_t>(p2)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(p2),
               static_cast<size_t>(p1)},
             std::vector<size_t>{static_cast<size_t>(p2),
               static_cast<size_t>(n)},
             std::vector<size_t>{static_cast<size_t>(p2),
               static_cast<size_t>(n)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(n)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "pi1");
    for (int sym1__ = 1; sym1__ <= p2; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= p1; ++sym2__) {
        param_names__.emplace_back(std::string() + "m1" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= p1; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= p2; ++sym2__) {
          param_names__.emplace_back(std::string() + "mt1" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= p2; ++sym2__) {
          param_names__.emplace_back(std::string() + "mx1" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= p2; ++sym2__) {
          param_names__.emplace_back(std::string() + "mx" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "pi1");
    for (int sym1__ = 1; sym1__ <= (p2 - 1); ++sym1__) {
      for (int sym2__ = 1; sym2__ <= p1; ++sym2__) {
        param_names__.emplace_back(std::string() + "m1" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= p1; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= p2; ++sym2__) {
          param_names__.emplace_back(std::string() + "mt1" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= p2; ++sym2__) {
          param_names__.emplace_back(std::string() + "mx1" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= p2; ++sym2__) {
          param_names__.emplace_back(std::string() + "mx" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"pi1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"m1\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(p1) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(p2) + "}},\"block\":\"parameters\"},{\"name\":\"mt1\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(p2) + ",\"cols\":" + std::to_string(p1) + "},\"block\":\"transformed_parameters\"},{\"name\":\"mx1\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(p2) + ",\"cols\":" + std::to_string(n) + "},\"block\":\"transformed_parameters\"},{\"name\":\"mx\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(p2) + ",\"cols\":" + std::to_string(n) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"pi1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"m1\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(p1) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string((p2 -1)) + "}},\"block\":\"parameters\"},{\"name\":\"mt1\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(p2) + ",\"cols\":" + std::to_string(p1) + "},\"block\":\"transformed_parameters\"},{\"name\":\"mx1\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(p2) + ",\"cols\":" + std::to_string(n) + "},\"block\":\"transformed_parameters\"},{\"name\":\"mx\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(p2) + ",\"cols\":" + std::to_string(n) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + (p1 * p2));
    const size_t num_transformed = emit_transformed_parameters * ((((p2 * p1)
      + (p2 * n)) + (p2 * n)));
    const size_t num_gen_quantities = emit_generated_quantities * (n);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + (p1 * p2));
    const size_t num_transformed = emit_transformed_parameters * ((((p2 * p1)
      + (p2 * n)) + (p2 * n)));
    const size_t num_gen_quantities = emit_generated_quantities * (n);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_compDAG1_namespace::model_compDAG1;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_compDAG1_namespace::profiles__;
}
#endif
#endif
